import java.util.*;
public class Person {

private int id;
private String name;
private String phone;
static int count=0;
 private static int autogenerated() {
	 int num=1325;
	 count++;
	 return num+count;
	 
 }
public Person()
{
	id=0;
	name=null;
	phone=null;
	}
public Person(String name, String ph)
{
	this.id=autogenerated();
	this.name=name;
	this.phone=ph;
}
public String toString() {
	return "id: "+this.id+"\n name:  "+this.name+"\n Mobile: "+this.phone;
}
public void setid(int id) {
	this.id=id;
}
public void setname(String name) {
	this.name=name;
}
public void setphone(String phone) {
	this.phone=phone;
}
public int getid() {
	return this.id;
}
public String getname() {
	return this.name;
}
public String getphone() {
	return this.phone;
}
}
